name: test-env
channels:
  - conda-forge
dependencies:
  # based on uv env pkg list
  - bmipy==2.0.1
  - certifi==2025.8.3
  #- cftime==1.6.4.post1
  - click==8.2.1
  - contourpy==1.3.3
  - cycler==0.12.1
  - fonttools==4.59.0
  - jinja2==3.1.6
  - kiwisolver==1.4.8
  - landlab==2.9.2
  - markdown-it-py==3.0.0
  - markupsafe==3.0.2
  - matplotlib==3.10.5
  - mdurl==0.1.2
  - mpi4py==4.1.0
  #- mypy-extensions==1.1.0
  - netcdf4==1.7.2
  - numpy==2.3.2
  - packaging==25.0
  - pandas==2.3.1
  - pathspec==0.12.1
  - patsy==1.0.1
  - pillow==11.3.0
  - platformdirs==4.3.8
  - pygments==2.19.2
  - pymetis==2025.2.1
  - pyparsing==3.2.3
  - pyshp==2.3.1
  - python-dateutil==2.9.0.post0
  - pytz==2025.2
  - pyyaml==6.0.2
  - rich==14.1.0
  - rich-click==1.8.9
  - scipy==1.16.0
  - six==1.17.0
  - statsmodels==0.14.5
  - typing-extensions==4.14.1
  #- tzdata==2025.2
  - xarray==2025.7.1
  # pkg versions not supported by conda
  - pip
  - pip:
    - mypy-extensions==1.1.0
    - tzdata==2025.2
    - cftime==1.6.4.post1